import {makeBlend,saveSale,day} from './operations';
import {recipeCost} from './cost';
export async function seedDemo(db:D1Database,owner:string){
 const restaurantId='demo:'+owner,date=new Date().toISOString(),record=(key:string,kind:string,data:any)=>db.prepare('INSERT INTO records(id,restaurant_id,kind,data,created) VALUES(?,?,?,?,?) ON CONFLICT(id) DO NOTHING').bind(restaurantId+':'+key,restaurantId,kind,JSON.stringify(data),date);
 const specs:any[]=[['veal','گوشت گاو','g',1000,700000,10000],['lamb','گوشت گوسفند','g',1000,950000,10000],['bun','نان برگر','piece',1,18000,100],['sausage','سوسیس هات‌داگ','g',1000,320000,10000],['hotbun','نان هات‌داگ','piece',1,18000,100],['ketchup','سس کچاپ','g',1000,85000,5000],['milk','شیر','ml',1000,55000,20000],['coffee','دانه قهوه','g',1000,950000,2000]];
 const items:any={};const queries:any[]=[db.prepare('INSERT INTO restaurants(id,owner,name,city,created) VALUES(?,?,?,?,?) ON CONFLICT(owner) DO NOTHING').bind(restaurantId,owner,'داینر آزمایشی نیما','نوشهر',date)];
 for(const [key,name,unit,packQuantity,toman,qty] of specs){const data={catalogId:key,name,unit,packQuantity,price:toman*10,source:'تستی — قیمت فرضی، مرجع بازار نیست',date};items[key]={...data,id:restaurantId+':'+key};queries.push(record(key,'ingredient',data));queries.push(db.prepare('INSERT INTO stock_lots(id,restaurant_id,ingredient_id,name,unit,initial,remaining,total_cost,supplier,expires,location,created) VALUES(?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO NOTHING').bind(restaurantId+':lot:'+key,restaurantId,items[key].id,name,unit,qty*1000,qty*1000,Math.round(data.price/packQuantity*qty),'فروشنده تستی',key==='coffee'?null:day(new Date(Date.now()+7*86400000)),'انبار تستی',date))}
 for(const [key,a,b] of [['mix70',70,30],['mix50',50,50]] as const){const d=makeBlend('مخلوط '+a+'٪ گاو و '+b+'٪ گوسفند',[{...items.veal,percent:a},{...items.lamb,percent:b}],restaurantId+':'+key);items[key]={...d,id:restaurantId+':'+key};queries.push(record(key,'ingredient',d))}
 for(const [key,name,parts,sale,pack] of [['burger','برگر مخلوط تستی',[['mix70',150],['bun',1],['ketchup',20]],230000,8000],['hotdog','هات‌داگ تستی',[['sausage',120],['hotbun',1],['ketchup',20]],160000,7000],['latte','لاته تستی',[['coffee',18],['milk',220]],110000,5000]] as any[]){const lines=parts.map(([k,q]:any)=>({...items[k],quantity:q,yield:100}));queries.push(record(key,'recipe',{name,servings:1,lines,...recipeCost(lines,1,sale*10,pack*10),date}))}
 queries.push(db.prepare('INSERT INTO stock_lots(id,restaurant_id,ingredient_id,name,unit,initial,remaining,total_cost,supplier,expires,location,created) VALUES(?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO NOTHING').bind(restaurantId+':expired-milk',restaurantId,items.milk.id,'شیر — نوبت تستی قدیمی','ml',1000000,800000,550000,'فروشنده تستی',day(new Date(Date.now()-86400000)),'یخچال تستی',date));
 queries.push(db.prepare('INSERT INTO stock_moves(id,restaurant_id,lot_id,quantity,cost,reason,created,applied) VALUES(?,?,?,?,?,?,?,1) ON CONFLICT(id) DO NOTHING').bind(restaurantId+':waste',restaurantId,restaurantId+':expired-milk',200000,110000,'دورریز نمونه تستی',date));
 await db.batch(queries);
 for(const [key,count,channel,price,pack,commission,delivery] of [['burger',3,'حضوری',230000,24000,0,0],['hotdog',2,'اسنپ',160000,14000,48000,25000],['latte',4,'بیرون‌بر',110000,20000,0,0]] as any[])await saveSale(db,restaurantId,restaurantId+':sale:'+key,{recipeId:restaurantId+':'+key,count,channel,unitPrice:price,pack,commission,delivery,deliveryReceived:0,discount:0});
}
