export const materials = [
{id:'milk',name:'شیر',icon:'🥛',unit:'ml',pack:'1000',group:'لبنیات',aliases:'شیر گاو'},
{id:'cheese',name:'پنیر پیتزا',icon:'🧀',unit:'g',pack:'1000',group:'لبنیات',aliases:'موزارلا'},
{id:'butter',name:'کره',icon:'🧈',unit:'g',pack:'100',group:'لبنیات',aliases:''},
{id:'cream',name:'خامه',icon:'🥛',unit:'g',pack:'200',group:'لبنیات',aliases:''},
{id:'beef',name:'گوشت چرخ‌کرده',icon:'🥩',unit:'g',pack:'1000',group:'پروتئین',aliases:'گوشت برگر'},
{id:'chicken',name:'سینه مرغ',icon:'🍗',unit:'g',pack:'1000',group:'پروتئین',aliases:'فیله مرغ'},
{id:'sausage',name:'سوسیس هات‌داگ',icon:'🌭',unit:'g',pack:'1000',group:'پروتئین',aliases:'سوسیس'},
{id:'egg',name:'تخم‌مرغ',icon:'🥚',unit:'piece',pack:'1',group:'پروتئین',aliases:''},
{id:'bun',name:'نان برگر',icon:'🍞',unit:'piece',pack:'1',group:'نان و خشکبار',aliases:'نان همبرگر'},
{id:'hotbun',name:'نان هات‌داگ',icon:'🥖',unit:'piece',pack:'1',group:'نان و خشکبار',aliases:'نان ساندویچ'},
{id:'flour',name:'آرد سفید',icon:'🌾',unit:'g',pack:'1000',group:'نان و خشکبار',aliases:''},
{id:'rice',name:'برنج',icon:'🍚',unit:'g',pack:'1000',group:'نان و خشکبار',aliases:''},
{id:'potato',name:'سیب‌زمینی',icon:'🥔',unit:'g',pack:'1000',group:'سبزی و میوه',aliases:'سیب زمینی'},
{id:'tomato',name:'گوجه‌فرنگی',icon:'🍅',unit:'g',pack:'1000',group:'سبزی و میوه',aliases:'گوجه'},
{id:'lettuce',name:'کاهو',icon:'🥬',unit:'g',pack:'1000',group:'سبزی و میوه',aliases:''},
{id:'onion',name:'پیاز',icon:'🧅',unit:'g',pack:'1000',group:'سبزی و میوه',aliases:''},
{id:'mushroom',name:'قارچ',icon:'🍄',unit:'g',pack:'1000',group:'سبزی و میوه',aliases:''},
{id:'lemon',name:'آب‌لیمو',icon:'🍋',unit:'ml',pack:'1000',group:'سبزی و میوه',aliases:'آب لیمو'},
{id:'coffee',name:'دانه قهوه',icon:'☕',unit:'g',pack:'1000',group:'نوشیدنی',aliases:'قهوه اسپرسو'},
{id:'tea',name:'چای خشک',icon:'🫖',unit:'g',pack:'500',group:'نوشیدنی',aliases:'چای'},
{id:'sugar',name:'شکر',icon:'🍬',unit:'g',pack:'1000',group:'سس و چاشنی',aliases:''},
{id:'oil',name:'روغن',icon:'🫗',unit:'ml',pack:'1000',group:'سس و چاشنی',aliases:'روغن سرخ کردنی'},
{id:'salt',name:'نمک',icon:'🧂',unit:'g',pack:'500',group:'سس و چاشنی',aliases:''},
{id:'ketchup',name:'سس کچاپ',icon:'🥫',unit:'g',pack:'1000',group:'سس و چاشنی',aliases:'سس گوجه'},
{id:'mayo',name:'سس مایونز',icon:'🥣',unit:'g',pack:'1000',group:'سس و چاشنی',aliases:''},
{id:'box',name:'جعبه غذا',icon:'📦',unit:'piece',pack:'1',group:'بسته‌بندی',aliases:'بسته بندی جعبه'},
{id:'cup',name:'لیوان بیرون‌بر',icon:'🥤',unit:'piece',pack:'1',group:'بسته‌بندی',aliases:'لیوان کاغذی'},
{id:'bag',name:'پاکت حمل',icon:'🛍️',unit:'piece',pack:'1',group:'بسته‌بندی',aliases:'کیسه پاکت'},
{"id": "yogurt", "name": "ماست ساده", "icon": "🥛", "unit": "g", "pack": "1000", "group": "لبنیات", "aliases": ""},
{"id": "greek", "name": "ماست چکیده", "icon": "🥛", "unit": "g", "pack": "1000", "group": "لبنیات", "aliases": ""},
{"id": "feta", "name": "پنیر سفید", "icon": "🥛", "unit": "g", "pack": "1000", "group": "لبنیات", "aliases": ""},
{"id": "cheddar", "name": "پنیر چدار", "icon": "🥛", "unit": "g", "pack": "1000", "group": "لبنیات", "aliases": ""},
{"id": "parmesan", "name": "پنیر پارمزان", "icon": "🥛", "unit": "g", "pack": "1000", "group": "لبنیات", "aliases": ""},
{"id": "creamcheese", "name": "پنیر خامه‌ای", "icon": "🥛", "unit": "g", "pack": "1000", "group": "لبنیات", "aliases": ""},
{"id": "kashk", "name": "کشک", "icon": "🥛", "unit": "g", "pack": "1000", "group": "لبنیات", "aliases": ""},
{"id": "doogh", "name": "دوغ", "icon": "🥛", "unit": "ml", "pack": "1000", "group": "لبنیات", "aliases": ""},
{"id": "icecream", "name": "بستنی وانیلی", "icon": "🥛", "unit": "g", "pack": "1000", "group": "لبنیات", "aliases": ""},
{"id": "condensed", "name": "شیرعسلی", "icon": "🥛", "unit": "g", "pack": "1000", "group": "لبنیات", "aliases": ""},
{"id": "lamb", "name": "گوشت گوسفندی", "icon": "🥩", "unit": "g", "pack": "1000", "group": "پروتئین", "aliases": ""},
{"id": "veal", "name": "گوشت گوساله تکه‌ای", "icon": "🥩", "unit": "g", "pack": "1000", "group": "پروتئین", "aliases": ""},
{"id": "thigh", "name": "ران مرغ", "icon": "🥩", "unit": "g", "pack": "1000", "group": "پروتئین", "aliases": ""},
{"id": "wings", "name": "بال مرغ", "icon": "🥩", "unit": "g", "pack": "1000", "group": "پروتئین", "aliases": ""},
{"id": "fish", "name": "فیله ماهی", "icon": "🥩", "unit": "g", "pack": "1000", "group": "پروتئین", "aliases": ""},
{"id": "shrimp", "name": "میگو", "icon": "🥩", "unit": "g", "pack": "1000", "group": "پروتئین", "aliases": ""},
{"id": "tuna", "name": "تن ماهی", "icon": "🥩", "unit": "g", "pack": "1000", "group": "پروتئین", "aliases": ""},
{"id": "ham", "name": "ژامبون", "icon": "🥩", "unit": "g", "pack": "1000", "group": "پروتئین", "aliases": ""},
{"id": "pepperoni", "name": "پپرونی", "icon": "🥩", "unit": "g", "pack": "1000", "group": "پروتئین", "aliases": ""},
{"id": "bacon", "name": "بیکن", "icon": "🥩", "unit": "g", "pack": "1000", "group": "پروتئین", "aliases": ""},
{"id": "liver", "name": "جگر", "icon": "🥩", "unit": "g", "pack": "1000", "group": "پروتئین", "aliases": ""},
{"id": "falafel", "name": "فلافل آماده", "icon": "🥩", "unit": "g", "pack": "1000", "group": "پروتئین", "aliases": ""},
{"id": "toast", "name": "نان تست", "icon": "🌾", "unit": "piece", "pack": "1", "group": "نان و خشکبار", "aliases": ""},
{"id": "pita", "name": "نان پیتا", "icon": "🌾", "unit": "piece", "pack": "1", "group": "نان و خشکبار", "aliases": ""},
{"id": "lavash", "name": "نان لواش", "icon": "🌾", "unit": "piece", "pack": "1", "group": "نان و خشکبار", "aliases": ""},
{"id": "baguette", "name": "نان باگت", "icon": "🌾", "unit": "piece", "pack": "1", "group": "نان و خشکبار", "aliases": ""},
{"id": "pizza", "name": "خمیر پیتزا", "icon": "🌾", "unit": "piece", "pack": "1", "group": "نان و خشکبار", "aliases": ""},
{"id": "pasta", "name": "پاستا خشک", "icon": "🌾", "unit": "g", "pack": "1000", "group": "نان و خشکبار", "aliases": ""},
{"id": "noodles", "name": "نودل", "icon": "🌾", "unit": "g", "pack": "1000", "group": "نان و خشکبار", "aliases": ""},
{"id": "oats", "name": "جو دوسر", "icon": "🌾", "unit": "g", "pack": "1000", "group": "نان و خشکبار", "aliases": ""},
{"id": "breadcrumbs", "name": "پودر سوخاری", "icon": "🌾", "unit": "g", "pack": "1000", "group": "نان و خشکبار", "aliases": ""},
{"id": "cornflour", "name": "نشاسته ذرت", "icon": "🌾", "unit": "g", "pack": "1000", "group": "نان و خشکبار", "aliases": ""},
{"id": "walnut", "name": "گردو", "icon": "🌾", "unit": "g", "pack": "1000", "group": "نان و خشکبار", "aliases": ""},
{"id": "almond", "name": "بادام", "icon": "🌾", "unit": "g", "pack": "1000", "group": "نان و خشکبار", "aliases": ""},
{"id": "pistachio", "name": "پسته", "icon": "🌾", "unit": "g", "pack": "1000", "group": "نان و خشکبار", "aliases": ""},
{"id": "sesame", "name": "کنجد", "icon": "🌾", "unit": "g", "pack": "1000", "group": "نان و خشکبار", "aliases": ""},
{"id": "raisin", "name": "کشمش", "icon": "🌾", "unit": "g", "pack": "1000", "group": "نان و خشکبار", "aliases": ""},
{"id": "date", "name": "خرما", "icon": "🌾", "unit": "g", "pack": "1000", "group": "نان و خشکبار", "aliases": ""},
{"id": "lentil", "name": "عدس", "icon": "🌾", "unit": "g", "pack": "1000", "group": "نان و خشکبار", "aliases": ""},
{"id": "chickpea", "name": "نخود", "icon": "🌾", "unit": "g", "pack": "1000", "group": "نان و خشکبار", "aliases": ""},
{"id": "bean", "name": "لوبیا چیتی", "icon": "🌾", "unit": "g", "pack": "1000", "group": "نان و خشکبار", "aliases": ""},
{"id": "redbean", "name": "لوبیا قرمز", "icon": "🌾", "unit": "g", "pack": "1000", "group": "نان و خشکبار", "aliases": ""},
{"id": "splitpea", "name": "لپه", "icon": "🌾", "unit": "g", "pack": "1000", "group": "نان و خشکبار", "aliases": ""},
{"id": "bulgur", "name": "بلغور", "icon": "🌾", "unit": "g", "pack": "1000", "group": "نان و خشکبار", "aliases": ""},
{"id": "cucumber", "name": "خیار", "icon": "🥬", "unit": "g", "pack": "1000", "group": "سبزی و میوه", "aliases": ""},
{"id": "pickle", "name": "خیارشور", "icon": "🥬", "unit": "g", "pack": "1000", "group": "سبزی و میوه", "aliases": ""},
{"id": "pepper", "name": "فلفل دلمه‌ای", "icon": "🥬", "unit": "g", "pack": "1000", "group": "سبزی و میوه", "aliases": ""},
{"id": "carrot", "name": "هویج", "icon": "🥬", "unit": "g", "pack": "1000", "group": "سبزی و میوه", "aliases": ""},
{"id": "cabbage", "name": "کلم سفید", "icon": "🥬", "unit": "g", "pack": "1000", "group": "سبزی و میوه", "aliases": ""},
{"id": "purplecabbage", "name": "کلم قرمز", "icon": "🥬", "unit": "g", "pack": "1000", "group": "سبزی و میوه", "aliases": ""},
{"id": "garlic", "name": "سیر", "icon": "🥬", "unit": "g", "pack": "1000", "group": "سبزی و میوه", "aliases": ""},
{"id": "spinach", "name": "اسفناج", "icon": "🥬", "unit": "g", "pack": "1000", "group": "سبزی و میوه", "aliases": ""},
{"id": "parsley", "name": "جعفری", "icon": "🥬", "unit": "g", "pack": "1000", "group": "سبزی و میوه", "aliases": ""},
{"id": "mint", "name": "نعناع", "icon": "🥬", "unit": "g", "pack": "1000", "group": "سبزی و میوه", "aliases": ""},
{"id": "basil", "name": "ریحان", "icon": "🥬", "unit": "g", "pack": "1000", "group": "سبزی و میوه", "aliases": ""},
{"id": "celery", "name": "کرفس", "icon": "🥬", "unit": "g", "pack": "1000", "group": "سبزی و میوه", "aliases": ""},
{"id": "eggplant", "name": "بادمجان", "icon": "🥬", "unit": "g", "pack": "1000", "group": "سبزی و میوه", "aliases": ""},
{"id": "zucchini", "name": "کدو سبز", "icon": "🥬", "unit": "g", "pack": "1000", "group": "سبزی و میوه", "aliases": ""},
{"id": "corn", "name": "ذرت", "icon": "🥬", "unit": "g", "pack": "1000", "group": "سبزی و میوه", "aliases": ""},
{"id": "peas", "name": "نخودفرنگی", "icon": "🥬", "unit": "g", "pack": "1000", "group": "سبزی و میوه", "aliases": ""},
{"id": "olive", "name": "زیتون", "icon": "🥬", "unit": "g", "pack": "1000", "group": "سبزی و میوه", "aliases": ""},
{"id": "banana", "name": "موز", "icon": "🥬", "unit": "g", "pack": "1000", "group": "سبزی و میوه", "aliases": ""},
{"id": "strawberry", "name": "توت‌فرنگی", "icon": "🥬", "unit": "g", "pack": "1000", "group": "سبزی و میوه", "aliases": ""},
{"id": "orange", "name": "پرتقال", "icon": "🥬", "unit": "g", "pack": "1000", "group": "سبزی و میوه", "aliases": ""},
{"id": "apple", "name": "سیب", "icon": "🥬", "unit": "g", "pack": "1000", "group": "سبزی و میوه", "aliases": ""},
{"id": "mango", "name": "انبه", "icon": "🥬", "unit": "g", "pack": "1000", "group": "سبزی و میوه", "aliases": ""},
{"id": "pineapple", "name": "آناناس", "icon": "🥬", "unit": "g", "pack": "1000", "group": "سبزی و میوه", "aliases": ""},
{"id": "watermelon", "name": "هندوانه", "icon": "🥬", "unit": "g", "pack": "1000", "group": "سبزی و میوه", "aliases": ""},
{"id": "kiwi", "name": "کیوی", "icon": "🥬", "unit": "g", "pack": "1000", "group": "سبزی و میوه", "aliases": ""},
{"id": "blackpepper", "name": "فلفل سیاه", "icon": "🧂", "unit": "g", "pack": "1000", "group": "سس و چاشنی", "aliases": ""},
{"id": "turmeric", "name": "زردچوبه", "icon": "🧂", "unit": "g", "pack": "1000", "group": "سس و چاشنی", "aliases": ""},
{"id": "paprika", "name": "پاپریکا", "icon": "🧂", "unit": "g", "pack": "1000", "group": "سس و چاشنی", "aliases": ""},
{"id": "cinnamon", "name": "دارچین", "icon": "🧂", "unit": "g", "pack": "1000", "group": "سس و چاشنی", "aliases": ""},
{"id": "cumin", "name": "زیره", "icon": "🧂", "unit": "g", "pack": "1000", "group": "سس و چاشنی", "aliases": ""},
{"id": "thyme", "name": "آویشن", "icon": "🧂", "unit": "g", "pack": "1000", "group": "سس و چاشنی", "aliases": ""},
{"id": "saffron", "name": "زعفران", "icon": "🧂", "unit": "g", "pack": "1000", "group": "سس و چاشنی", "aliases": ""},
{"id": "cardamom", "name": "هل", "icon": "🧂", "unit": "g", "pack": "1000", "group": "سس و چاشنی", "aliases": ""},
{"id": "vanilla", "name": "وانیل", "icon": "🧂", "unit": "g", "pack": "1000", "group": "سس و چاشنی", "aliases": ""},
{"id": "baking", "name": "بیکینگ‌پودر", "icon": "🧂", "unit": "g", "pack": "1000", "group": "سس و چاشنی", "aliases": ""},
{"id": "yeast", "name": "خمیرمایه", "icon": "🧂", "unit": "g", "pack": "1000", "group": "سس و چاشنی", "aliases": ""},
{"id": "mustard", "name": "سس خردل", "icon": "🧂", "unit": "g", "pack": "1000", "group": "سس و چاشنی", "aliases": ""},
{"id": "bbq", "name": "سس باربیکیو", "icon": "🧂", "unit": "g", "pack": "1000", "group": "سس و چاشنی", "aliases": ""},
{"id": "hot", "name": "سس تند", "icon": "🧂", "unit": "g", "pack": "1000", "group": "سس و چاشنی", "aliases": ""},
{"id": "soy", "name": "سس سویا", "icon": "🧂", "unit": "ml", "pack": "1000", "group": "سس و چاشنی", "aliases": ""},
{"id": "vinegar", "name": "سرکه", "icon": "🧂", "unit": "ml", "pack": "1000", "group": "سس و چاشنی", "aliases": ""},
{"id": "tomatopaste", "name": "رب گوجه‌فرنگی", "icon": "🧂", "unit": "g", "pack": "1000", "group": "سس و چاشنی", "aliases": ""},
{"id": "pomegranate", "name": "رب انار", "icon": "🧂", "unit": "g", "pack": "1000", "group": "سس و چاشنی", "aliases": ""},
{"id": "honey", "name": "عسل", "icon": "🧂", "unit": "g", "pack": "1000", "group": "سس و چاشنی", "aliases": ""},
{"id": "chocolate", "name": "شکلات", "icon": "🧂", "unit": "g", "pack": "1000", "group": "سس و چاشنی", "aliases": ""},
{"id": "cocoa", "name": "پودر کاکائو", "icon": "🧂", "unit": "g", "pack": "1000", "group": "سس و چاشنی", "aliases": ""},
{"id": "caramel", "name": "سس کارامل", "icon": "🧂", "unit": "g", "pack": "1000", "group": "سس و چاشنی", "aliases": ""},
{"id": "syrup", "name": "سیروپ وانیل", "icon": "🧂", "unit": "ml", "pack": "1000", "group": "سس و چاشنی", "aliases": ""},
{"id": "rosewater", "name": "گلاب", "icon": "🧂", "unit": "ml", "pack": "1000", "group": "سس و چاشنی", "aliases": ""},
{"id": "water", "name": "آب آشامیدنی", "icon": "🥤", "unit": "ml", "pack": "1000", "group": "نوشیدنی", "aliases": ""},
{"id": "soda", "name": "آب گازدار", "icon": "🥤", "unit": "ml", "pack": "1000", "group": "نوشیدنی", "aliases": ""},
{"id": "orangejuice", "name": "آب پرتقال", "icon": "🥤", "unit": "ml", "pack": "1000", "group": "نوشیدنی", "aliases": ""},
{"id": "cola", "name": "نوشابه", "icon": "🥤", "unit": "ml", "pack": "1000", "group": "نوشیدنی", "aliases": ""},
{"id": "malt", "name": "ماءالشعیر", "icon": "🥤", "unit": "ml", "pack": "1000", "group": "نوشیدنی", "aliases": ""},
{"id": "matcha", "name": "پودر ماچا", "icon": "🥤", "unit": "g", "pack": "1000", "group": "نوشیدنی", "aliases": ""},
{"id": "instantcoffee", "name": "قهوه فوری", "icon": "🥤", "unit": "g", "pack": "1000", "group": "نوشیدنی", "aliases": ""},
{"id": "lid", "name": "درب لیوان", "icon": "📦", "unit": "piece", "pack": "1", "group": "بسته‌بندی", "aliases": ""},
{"id": "straw", "name": "نی", "icon": "📦", "unit": "piece", "pack": "1", "group": "بسته‌بندی", "aliases": ""},
{"id": "napkin", "name": "دستمال کاغذی", "icon": "📦", "unit": "piece", "pack": "1", "group": "بسته‌بندی", "aliases": ""},
{"id": "fork", "name": "چنگال یکبارمصرف", "icon": "📦", "unit": "piece", "pack": "1", "group": "بسته‌بندی", "aliases": ""},
{"id": "spoon", "name": "قاشق یکبارمصرف", "icon": "📦", "unit": "piece", "pack": "1", "group": "بسته‌بندی", "aliases": ""},
{"id": "saucecup", "name": "ظرف سس", "icon": "📦", "unit": "piece", "pack": "1", "group": "بسته‌بندی", "aliases": ""},
{"id": "pizzabox", "name": "جعبه پیتزا", "icon": "📦", "unit": "piece", "pack": "1", "group": "بسته‌بندی", "aliases": ""},
{"id": "foil", "name": "ورق آلومینیوم", "icon": "📦", "unit": "piece", "pack": "1", "group": "بسته‌بندی", "aliases": ""},
{"id": "glove", "name": "دستکش یکبارمصرف", "icon": "📦", "unit": "piece", "pack": "1", "group": "بسته‌بندی", "aliases": ""}
];
export type Material=typeof materials[number];
export const recipes=[
{id:'latte',name:'لاته',icon:'☕',lines:[['coffee',18],['milk',220]]},
{id:'espresso',name:'اسپرسو',icon:'☕',lines:[['coffee',18]]},
{id:'hotdog',name:'هات‌داگ کلاسیک',icon:'🌭',lines:[['hotbun',1],['sausage',100],['ketchup',20]]},
{id:'cheeseburger',name:'چیزبرگر',icon:'🍔',lines:[['bun',1],['beef',150],['cheese',25],['lettuce',15],['tomato',25],['mayo',20],['salt',1]]},
{id:'omelette',name:'املت گوجه',icon:'🍳',lines:[['egg',2],['tomato',150],['oil',10],['salt',1]]},
{"id": "americano", "name": "آمریکانو", "icon": "☕", "lines": [["coffee", 18], ["water", 150]]},
{"id": "cappuccino", "name": "کاپوچینو", "icon": "☕", "lines": [["coffee", 18], ["milk", 150]]},
{"id": "mocha", "name": "موکا", "icon": "☕", "lines": [["coffee", 18], ["milk", 180], ["chocolate", 20]]},
{"id": "hotchocolate", "name": "هات‌چاکلت", "icon": "🍫", "lines": [["milk", 220], ["cocoa", 12], ["sugar", 15]]},
{"id": "matchalatte", "name": "ماچا لاته", "icon": "🍵", "lines": [["matcha", 3], ["milk", 200], ["water", 40]]},
{"id": "tea", "name": "چای", "icon": "🫖", "lines": [["tea", 3], ["water", 200]]},
{"id": "lemonade", "name": "لیموناد", "icon": "🍋", "lines": [["lemon", 30], ["water", 200], ["sugar", 20]]},
{"id": "mojito", "name": "موهیتو بدون الکل", "icon": "🍹", "lines": [["lemon", 25], ["soda", 200], ["mint", 5], ["sugar", 20]]},
{"id": "bananashake", "name": "شیک موز", "icon": "🍌", "lines": [["banana", 100], ["milk", 150], ["icecream", 100]]},
{"id": "chocshake", "name": "شیک شکلات", "icon": "🍫", "lines": [["milk", 150], ["icecream", 120], ["chocolate", 25]]},
{"id": "strawberryshake", "name": "شیک توت‌فرنگی", "icon": "🍓", "lines": [["strawberry", 100], ["milk", 150], ["icecream", 100]]},
{"id": "burger", "name": "همبرگر", "icon": "🍔", "lines": [["bun", 1], ["beef", 150], ["lettuce", 15], ["tomato", 25], ["pickle", 20], ["ketchup", 20], ["salt", 1]]},
{"id": "mushroomburger", "name": "قارچ‌برگر", "icon": "🍔", "lines": [["bun", 1], ["beef", 150], ["mushroom", 50], ["cheese", 25], ["oil", 5], ["mayo", 20], ["salt", 1]]},
{"id": "cheesehotdog", "name": "چیزهات‌داگ", "icon": "🌭", "lines": [["hotbun", 1], ["sausage", 100], ["cheese", 25], ["ketchup", 20]]},
{"id": "bandari", "name": "ساندویچ بندری", "icon": "🥖", "lines": [["hotbun", 1], ["sausage", 100], ["onion", 60], ["tomatopaste", 20], ["oil", 10], ["paprika", 1], ["salt", 1]]},
{"id": "chickensandwich", "name": "ساندویچ مرغ", "icon": "🥪", "lines": [["baguette", 1], ["chicken", 150], ["lettuce", 20], ["tomato", 30], ["mayo", 20], ["oil", 5], ["salt", 1]]},
{"id": "grilledcheese", "name": "تست پنیر", "icon": "🥪", "lines": [["toast", 2], ["cheddar", 50], ["butter", 10]]},
{"id": "margherita", "name": "پیتزا مارگاریتا", "icon": "🍕", "lines": [["pizza", 1], ["cheese", 100], ["tomatopaste", 30], ["basil", 5], ["oil", 5]]},
{"id": "pepperonipizza", "name": "پیتزا پپرونی", "icon": "🍕", "lines": [["pizza", 1], ["cheese", 100], ["pepperoni", 60], ["tomatopaste", 30], ["thyme", 1]]},
{"id": "vegpizza", "name": "پیتزا سبزیجات", "icon": "🍕", "lines": [["pizza", 1], ["cheese", 100], ["pepper", 30], ["mushroom", 50], ["corn", 30], ["tomatopaste", 30]]},
{"id": "alfredo", "name": "پاستا مرغ و قارچ", "icon": "🍝", "lines": [["pasta", 100], ["chicken", 100], ["mushroom", 60], ["cream", 60], ["milk", 50], ["butter", 10], ["parmesan", 15], ["salt", 1]]},
{"id": "tomatopasta", "name": "پاستا گوجه", "icon": "🍝", "lines": [["pasta", 100], ["tomato", 120], ["tomatopaste", 20], ["garlic", 5], ["oil", 10], ["basil", 3], ["salt", 1]]},
{"id": "shirazisalad", "name": "سالاد شیرازی", "icon": "🥗", "lines": [["cucumber", 80], ["tomato", 80], ["onion", 30], ["lemon", 15], ["mint", 2], ["salt", 1]]},
{"id": "greensalad", "name": "سالاد فصل", "icon": "🥗", "lines": [["lettuce", 100], ["tomato", 50], ["cucumber", 50], ["carrot", 20], ["lemon", 15], ["oil", 5]]},
{"id": "yogurtcucumber", "name": "ماست و خیار", "icon": "🥣", "lines": [["yogurt", 150], ["cucumber", 50], ["mint", 2], ["salt", 1]]},
{"id": "friedegg", "name": "نیمرو", "icon": "🍳", "lines": [["egg", 2], ["butter", 10], ["salt", 1]]},
{"id": "pancake", "name": "پنکیک", "icon": "🥞", "lines": [["flour", 60], ["milk", 80], ["egg", 1], ["sugar", 15], ["butter", 10], ["baking", 2]]},
{"id": "frenchtoast", "name": "فرنچ‌تست", "icon": "🍞", "lines": [["toast", 2], ["egg", 1], ["milk", 50], ["butter", 10], ["sugar", 10], ["cinnamon", 1]]},
{"id": "rice", "name": "برنج ساده", "icon": "🍚", "lines": [["rice", 100], ["water", 200], ["oil", 5], ["salt", 1]]},
{"id": "joojeh", "name": "جوجه‌کباب", "icon": "🍢", "lines": [["chicken", 200], ["onion", 40], ["yogurt", 20], ["lemon", 10], ["oil", 10], ["salt", 1]]},
{"id": "koobideh", "name": "کباب کوبیده", "icon": "🍢", "lines": [["beef", 180], ["onion", 40], ["salt", 2], ["blackpepper", 1]]}
];
export type Template=typeof recipes[number];
export const normalize=(s:string)=>s.replace(/[‌\s-]/g,'').replace(/ي/g,'ی').replace(/ك/g,'ک');
export function matchingIngredient(item:Material,rows:any[]){return rows.find(r=>r.data.unit===item.unit&&(r.data.catalogId===item.id||normalize(r.data.name)===normalize(item.name)));}
