'use client';
import {useState} from 'react';
import {Input} from '@/components/ui/input';
import {Button} from '@/components/ui/button';
export function MenuBuilder({recipes,records,busy,submit}:{recipes:any[];records:any[];busy:boolean;submit:any}){
 const [selected,setSelected]=useState<string[]>([]);
 const menus=records.filter(r=>r.kind==='public_menu');
 const link=(data:any)=>'https://nimania.github.io/diner/menu.html#'+btoa(String.fromCharCode(...new TextEncoder().encode(JSON.stringify(data))));
 return <><section className="panel"><h2>🍽️ منوی آنلاین مشتری</h2><p>فقط نام مجموعه، توضیح غذا و قیمت فروش منتشر می‌شود. اطلاعات هزینه، رسپی و انبار در لینک قرار نمی‌گیرد.</p><form onSubmit={e=>submit(e,'public_menu')}><label>نام نمایشی مجموعه<Input name="name" required maxLength={100}/></label><label>توضیح کوتاه منو<Input name="description" maxLength={300}/></label><input type="hidden" name="recipeIds" value={JSON.stringify(selected)}/><div className="picture-grid">{recipes.map(r=><button type="button" className="picture-card" aria-pressed={selected.includes(r.id)} key={r.id} onClick={()=>setSelected(selected.includes(r.id)?selected.filter(id=>id!==r.id):[...selected,r.id])}><span>{selected.includes(r.id)?'✅':'🍽️'}</span><strong>{r.data.name}</strong><small>{new Intl.NumberFormat('fa-IR').format(r.data.sale/10)} تومان</small></button>)}</div>{selected.map(id=><label key={id}>توضیح {recipes.find(r=>r.id===id)?.data.name}<Input name={'description:'+id} maxLength={200}/><span>دسته‌بندی</span><Input name={'category:'+id} maxLength={60} defaultValue="غذا و نوشیدنی"/></label>)}<Button disabled={busy||!selected.length||selected.length>30}>ذخیره منو و ساخت لینک عمومی</Button></form></section><section className="panel"><h2>نسخه‌های منوی من</h2><p>هر لینک یک نسخه ثابت است. تغییر قیمت نیاز به ذخیره و اشتراک لینک جدید دارد؛ لینک قدیمی لغو نمی‌شود. این منو فعلاً سفارش‌گیری و پرداخت ندارد.</p>{menus.map(m=><article className="saved" key={m.id}><h3>{m.data.name}</h3><p>{m.data.items.length} محصول • {new Date(m.created).toLocaleDateString('fa-IR')}</p><a className="menu-public-link" href={link(m.data)} target="_blank" rel="noreferrer">بازکردن منوی عمومی ↗</a><label>لینک اشتراک (انتخاب و کپی کن)<Input readOnly value={link(m.data)} onFocus={e=>e.target.select()} dir="ltr"/></label></article>)}</section></>;
}
