"use client";
import {useState} from 'react';
import {materials,recipes,Material,Template,normalize,matchingIngredient} from '@/lib/library';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
export function MaterialPicker({onChoose}:{onChoose:(m:Material)=>void}){
 const [query,setQuery]=useState(''),[group,setGroup]=useState('همه');
 const list=materials.filter(m=>(group==='همه'||m.group===group)&&normalize(m.name+' '+m.aliases).includes(normalize(query)));
 return <section><h2>چی می‌خواهی اضافه کنی؟</h2><div className="library-filter"><Input aria-label="جست‌وجوی مواد" value={query} onChange={e=>setQuery(e.target.value)} placeholder="اسمش را بنویس؛ مثلاً شیر"/><Select value={group} onValueChange={setGroup}><SelectTrigger aria-label="دسته مواد"><SelectValue/></SelectTrigger><SelectContent>{['همه',...new Set(materials.map(m=>m.group))].map(g=><SelectItem key={g} value={g}>{g}</SelectItem>)}</SelectContent></Select></div><div className="picture-grid">{list.map(m=><button type="button" className="picture-card" key={m.id} onClick={()=>onChoose(m)}><span aria-hidden="true">{m.icon}</span><strong>{m.name}</strong></button>)}</div>{!list.length&&<p>پیدا نشد؛ می‌توانی ماده خودت را اضافه کنی.</p>}<Button type="button" variant="outline" onClick={()=>onChoose({id:'',name:'',icon:'➕',unit:'g',pack:'',group:'',aliases:''})}>ماده من در فهرست نیست</Button></section>
}
export function IngredientWizard({onSubmit,busy}:{onSubmit:(e:React.FormEvent<HTMLFormElement>)=>Promise<void>;busy:boolean}){
 const [item,setItem]=useState<Material|null>(null),[step,setStep]=useState(0),[unit,setUnit]=useState('g'),[review,setReview]=useState<Record<string,string>>({});
 const units:any={g:'گرم',ml:'میلی‌لیتر',piece:'عدد'};
 if(!item)return <MaterialPicker onChoose={m=>{setItem(m);setUnit(m.unit);setStep(0)}}/>;
 function next(form:HTMLFormElement){const area=form.querySelector('[data-step="'+step+'"]');const fields=area?.querySelectorAll('input')||[];for(const field of fields){if(!field.reportValidity())return}setReview(Object.fromEntries(new FormData(form)) as Record<string,string>);setStep(step+1)}
 return <section><Button type="button" variant="outline" onClick={()=>setItem(null)}>برگشت به فهرست</Button><div className="selected-picture"><span aria-hidden="true">{item.icon}</span><h2>{item.name||'ماده جدید'}</h2></div><p className="step-label">مرحله {['۱','۲','۳'][step]} از ۳ • {['نام و اندازه بسته','قیمت و منبع','بررسی و ثبت'][step]}</p><form key={item.id} onSubmit={async e=>{await onSubmit(e)}}><input type="hidden" name="unit" value={unit}/><input type="hidden" name="catalogId" value={item.id}/><div data-step="0" hidden={step!==0}><label>اسم ماده<Input name="name" required maxLength={200} defaultValue={item.name}/></label><label>اندازه بسته را با چه واحدی می‌گویی؟<Select value={unit} onValueChange={setUnit}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="g">گرم</SelectItem><SelectItem value="ml">میلی‌لیتر</SelectItem><SelectItem value="piece">عدد</SelectItem></SelectContent></Select></label><label>داخل یک بسته چند {units[unit]} است؟<Input required name="packQuantity" defaultValue={item.pack} inputMode="decimal"/></label><p>اندازه پیشنهادی را با بسته خودت چک کن. یک کیلو = ۱۰۰۰ گرم؛ یک لیتر = ۱۰۰۰ میلی‌لیتر.</p></div><div data-step="1" hidden={step!==1}><label>قیمت همین یک بسته چند تومان است؟<Input required name="price" inputMode="decimal"/></label><label>این قیمت را از کجا آوردی؟<Input name="source" required maxLength={200} placeholder="مثلاً فاکتور پخش احمدی"/></label></div>{step===2&&<div className="note"><h3>این اطلاعات درست است؟</h3><p>{review.name} • {review.packQuantity} {units[unit]}</p><p>قیمت بسته: {review.price} تومان</p><p>منبع: {review.source}</p><p>با ثبت، این ماده به فهرست قیمت‌های مجموعه اضافه می‌شود. هنوز موجودی انبار یا خرید ثبت نمی‌شود.</p><p>برای بررسی عددها، «قبلی» را بزن.</p></div>}<div className="actions">{step>0&&<Button type="button" variant="outline" onClick={()=>setStep(step-1)}>قبلی</Button>}{step<2?<Button type="button" onClick={e=>next(e.currentTarget.form!)}>بعدی</Button>:<Button disabled={busy}>{busy?'در حال ثبت…':'ثبت ماده'}</Button>}</div></form></section>
}
export function RecipePicker({rows,onChoose,onMissing}:{rows:any[];onChoose:(t:Template)=>void;onMissing:()=>void}){
 const [selected,setSelected]=useState<Template|null>(null),[query,setQuery]=useState('');
 const missing=selected?.lines.map(([id])=>materials.find(m=>m.id===id)!).filter(m=>!matchingIngredient(m,rows))||[];
 return <section className="panel"><h2>چه غذایی درست می‌کنی؟</h2><p>یکی را انتخاب کن؛ مقدارهای پیشنهادی را بعدش مطابق کار خودت تغییر بده.</p><Input aria-label="جست‌وجوی غذا" placeholder="اسم غذا یا نوشیدنی را جست‌وجو کن" value={query} onChange={e=>setQuery(e.target.value)}/><div className="picture-grid recipes-pictures">{recipes.filter(t=>normalize(t.name).includes(normalize(query))).map(t=><button className="picture-card" type="button" key={t.id} aria-pressed={selected?.id===t.id} onClick={()=>setSelected(t)}><span aria-hidden="true">{t.icon}</span><strong>{t.name}</strong></button>)}</div>{selected&&<div className="note"><h3>{selected.name} • دستور پیشنهادی برای یک پرس</h3><p>این الگو استاندارد قطعی نیست؛ سس، مخلفات و مقدارهای مجموعه‌ات را بررسی کن. الگوها نقطه شروع‌اند؛ آب، روغن، ادویه، سس و مخلفات واقعی خودت را بررسی کن.</p>{missing.length?<><p>اول قیمت این مواد را ثبت کن: {missing.map(m=>m.name).join('، ')}. هیچ ماده‌ای از دستور حذف نمی‌شود.</p><Button onClick={onMissing}>رفتن به مواد اولیه</Button></>:<Button onClick={()=>onChoose(selected)}>استفاده از این دستور و اصلاح مقدارها</Button>}</div>}</section>
}
