"use client";
import {useEffect,useState} from "react";
import {SidebarProvider,Sidebar,SidebarHeader,SidebarContent,SidebarMenu,SidebarMenuItem,SidebarMenuButton,SidebarInset,SidebarTrigger,SidebarFooter} from "@/components/ui/sidebar";
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from "@/components/ui/table";
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from "@/components/ui/select";
import {Button} from "@/components/ui/button";
import {Input} from "@/components/ui/input";
import {Skeleton} from "@/components/ui/skeleton";
import {toast,Toaster} from "sonner";
type Rec={id:string;kind:string;created:string;data:any};
const fmt=(n:number)=>new Intl.NumberFormat("fa-IR",{maximumFractionDigits:1}).format(n);
const tm=(n:number)=>fmt(n/10)+" تومان";
const units:any={g:"گرم",ml:"میلی‌لیتر",piece:"عدد"};
function Field({title,name,value,placeholder}:{title:string;name:string;value?:string;placeholder?:string}){return <label>{title}<Input name={name} defaultValue={value} required maxLength={200} placeholder={placeholder}/></label>}
export default function Workspace({displayName}:{displayName:string}){
 const [state,setState]=useState<{restaurant:any;records:Rec[]}|null>(null),[error,setError]=useState(""),[busy,setBusy]=useState(false),[view,setView]=useState("overview"),[unit,setUnit]=useState("g"),[lines,setLines]=useState<{key:string;id:string}[]>([]);
 async function load(){const r=await fetch("/api/data",{cache:"no-store"});const d=await r.json() as {restaurant:any;records:Rec[];error?:string};if(!r.ok)throw Error(d.error);setState(d);setError("")}
 useEffect(()=>{load().catch(e=>setError(e.message));const context=(document as any).modelContext;const life=new AbortController();if(context?.registerTool){try{Promise.resolve(context.registerTool({name:"read_diner_records",description:"Read records belonging to the signed-in restaurant; does not change data.",inputSchema:{type:"object",properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},async execute(input:any){if(!input||Object.keys(input).length)throw Error("No arguments expected");const r=await fetch("/api/data");if(!r.ok)throw Error("Access unavailable");return await r.json();}},{signal:life.signal})).catch(()=>{});}catch{}}return()=>life.abort();},[]);
 const ingredients=state?.records.filter(r=>r.kind==="ingredient")||[],recipes=state?.records.filter(r=>r.kind==="recipe")||[],waste=state?.records.filter(r=>r.kind==="waste")||[];
 async function submit(event:React.FormEvent<HTMLFormElement>,kind:string){
 event.preventDefault();const form=event.currentTarget;if(busy)return;setBusy(true);
 const id=form.dataset.requestId||crypto.randomUUID();form.dataset.requestId=id;
 const data:any={...Object.fromEntries(new FormData(form)),kind,id};
 if(kind==="ingredient")data.unit=unit;
 if(kind==="recipe")data.lines=lines.map(l=>({id:l.id,quantity:data["q"+l.key],yield:data["y"+l.key]}));
 try{const r=await fetch("/api/data",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(data)});const result=await r.json() as {error?:string};if(!r.ok){if(r.status<500)delete form.dataset.requestId;throw Error(result.error)}
 await load();delete form.dataset.requestId;form.reset();if(kind==="recipe")setLines([]);toast.success("ثبت شد و در حساب مجموعه ذخیره شد.");
 }catch(e){toast.error(e instanceof Error?e.message:"ذخیره انجام نشد")}finally{setBusy(false)}
 }
 const nav=[["overview","نمای مجموعه"],["ingredients","مواد اولیه"],["recipes","رسپی و هزینه"],["waste","ضایعات"],["next","بخش‌های بعدی"]];
 return <SidebarProvider><Sidebar side="right"><SidebarHeader><div className="brand">داینر<small>DINER / WORKSPACE</small></div><div className="identity">{state?.restaurant?.name||"مجموعه جدید"}<small>{displayName}</small></div></SidebarHeader><SidebarContent><SidebarMenu>{nav.map(([id,title])=><SidebarMenuItem key={id}><SidebarMenuButton isActive={view===id} onClick={()=>setView(id)}>{title}</SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu></SidebarContent><SidebarFooter><a href="https://nimania.github.io/diner/" target="_blank" rel="noreferrer">پیش‌نمایش همه پنل‌ها</a><a href="/signout-with-chatgpt?return_to=/" target="_top">خروج از حساب</a></SidebarFooter></Sidebar><SidebarInset><main className="work"><header><div><p>داینر / {state?.restaurant?.city||"شروع کار"}</p><h1>{nav.find(n=>n[0]===view)?.[1]}</h1></div><SidebarTrigger aria-label="باز کردن فهرست"/></header>
 {error?<section className="panel"><p role="alert">{error}</p><Button onClick={()=>load().catch(e=>setError(e.message))}>تلاش دوباره</Button></section>:!state?<Skeleton className="h-48 w-full"/>:!state.restaurant?<section className="panel onboarding"><h2>مجموعه‌ات را ثبت کن</h2><p>اطلاعات این مجموعه به حساب فعلی متصل می‌شود.</p><form onSubmit={e=>submit(e,"restaurant")}><Field name="name" title="نام رستوران یا کافه" placeholder="مثلاً داینر ساحل"/><Field name="city" title="شهر" placeholder="نوشهر"/><Button disabled={busy}>ثبت مجموعه</Button></form></section>:<>
 {view==="overview"&&<><div className="stats"><article><small>مواد اولیه</small><strong>{fmt(ingredients.length)}</strong><span>همراه با منبع قیمت</span></article><article><small>نسخه‌های رسپی</small><strong>{fmt(recipes.length)}</strong><span>قیمت زمان ثبت محفوظ است</span></article><article className="accent"><small>ارزش دورریز ثبت‌شده</small><strong>{tm(waste.reduce((s,r)=>s+r.data.cost,0))}</strong><span>مجموع ثبت‌ها؛ نه گزارش سود</span></article></div><section className="panel"><h2>از یک محصول پرفروش شروع کن</h2><p>ابتدا مواد اولیه را با قیمت بسته ثبت کن؛ بعد مقدار مصرف و تعداد پرس را وارد کن.</p><div className="actions"><Button onClick={()=>setView("ingredients")}>ثبت مواد اولیه</Button><Button variant="outline" onClick={()=>setView("recipes")}>ساخت رسپی</Button></div></section><p className="note">فروش، ارسال و هزینه‌های جاری هنوز متصل نیستند؛ بنابراین سود کل مجموعه در این نسخه نمایش داده نمی‌شود.</p></>}
 {view==="ingredients"&&<div className="columns"><section className="panel"><h2>ثبت ماده و قیمت خرید</h2><p>قیمت کل بسته را وارد کن؛ تبدیل به واحد مصرف خودکار است.</p><form onSubmit={e=>submit(e,"ingredient")}><Field name="name" title="نام ماده"/><label>واحد مقدار<Select value={unit} onValueChange={setUnit}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="g">گرم</SelectItem><SelectItem value="ml">میلی‌لیتر</SelectItem><SelectItem value="piece">عدد</SelectItem></SelectContent></Select></label><Field name="packQuantity" title={"مقدار داخل بسته ("+units[unit]+")"} placeholder="مثلاً ۱۰۰۰"/><Field name="price" title="قیمت کل بسته (تومان)"/><Field name="source" title="منبع قیمت" placeholder="فاکتور یا نام تأمین‌کننده"/><Button disabled={busy}>ثبت ماده</Button></form></section><section className="panel"><h2>دفتر مواد</h2>{!ingredients.length?<p>هنوز ماده‌ای ثبت نشده است.</p>:<Table><TableHeader><TableRow><TableHead>ماده</TableHead><TableHead>قیمت بسته</TableHead><TableHead>منبع</TableHead></TableRow></TableHeader><TableBody>{ingredients.map(r=><TableRow key={r.id}><TableCell>{r.data.name}<small>{fmt(r.data.packQuantity)} {units[r.data.unit]}</small></TableCell><TableCell>{tm(r.data.price)}</TableCell><TableCell>{r.data.source}<small>{new Date(r.created).toLocaleDateString("fa-IR")}</small></TableCell></TableRow>)}</TableBody></Table>}</section></div>}
 {view==="recipes"&&<><section className="panel"><h2>ساخت نسخه رسپی</h2><p>مقدار قابل‌مصرف مواد برای کل دستور است. افت آماده‌سازی با بازده محاسبه می‌شود.</p>{!ingredients.length?<Button onClick={()=>setView("ingredients")}>ابتدا ماده اولیه ثبت کن</Button>:<form onSubmit={e=>submit(e,"recipe")}><div className="pair"><Field name="name" title="نام محصول"/><Field name="servings" title="تعداد پرس خروجی" value="1"/></div>{lines.map(l=><div className="recipe-line" key={l.key}><label>ماده<Select value={l.id} onValueChange={id=>setLines(lines.map(x=>x.key===l.key?{...x,id}:x))}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{ingredients.map(i=><SelectItem value={i.id} key={i.id}>{i.data.name} • {units[i.data.unit]}</SelectItem>)}</SelectContent></Select></label><Field name={"q"+l.key} title="مقدار مصرف در کل دستور"/><Field name={"y"+l.key} title="بازده (%)" value="100"/><Button type="button" variant="outline" onClick={()=>setLines(lines.filter(x=>x.key!==l.key))}>حذف ردیف</Button></div>)}<Button type="button" variant="outline" onClick={()=>setLines([...lines,{key:crypto.randomUUID(),id:ingredients[0].id}])}>افزودن ماده +</Button><div className="pair"><Field name="pack" title="بسته‌بندی هر پرس (تومان)" value="0"/><Field name="sale" title="فروش هر پرس (تومان)"/></div><Button disabled={busy||!lines.length}>محاسبه و ذخیره نسخه</Button></form>}</section><section className="panel"><h2>رسپی‌های ذخیره‌شده</h2><p>باقی‌مانده و حاشیه، فقط پس از کسر مواد و بسته‌بندی هستند؛ سود خالص نیستند.</p>{!recipes.length?<p>هنوز رسپی ثبت نشده است.</p>:recipes.map(r=><article className="saved" key={r.id}><h3>{r.data.name}</h3><div className="metrics"><span>مواد: <b>{tm(r.data.food)}</b></span><span>بسته‌بندی: <b>{tm(r.data.pack)}</b></span><span>باقی‌مانده: <b>{tm(r.data.remaining)}</b></span><span>حاشیه: <b>{r.data.margin===null?"تعریف‌نشده":fmt(r.data.margin*100)+"٪"}</b></span></div><details><summary>مواد و منابع این نسخه</summary>{r.data.lines.map((l:any,i:number)=><p key={i}>{l.name} • {fmt(l.quantity)} {units[l.unit]} • بازده {fmt(l.yield)}٪ • {l.source}</p>)}</details></article>)}</section></>}
 {view==="waste"&&<div className="columns"><section className="panel"><h2>ثبت دورریز</h2><p>ارزش مواد را وارد کن، نه قیمت فروش غذا. غذای پرسنل را اینجا ثبت نکن.</p><form onSubmit={e=>submit(e,"waste")}><Field title="نام ماده" name="name"/><Field title="مقدار با واحد" name="quantity" placeholder="مثلاً ۶ عدد"/><Field title="ارزش مواد (تومان)" name="cost"/><Field title="علت" name="reason"/><Button disabled={busy}>ثبت دورریز</Button></form></section><section className="panel"><h2>دفتر ضایعات</h2>{!waste.length?<p>هنوز دورریزی ثبت نشده است.</p>:waste.map(r=><article className="saved" key={r.id}><h3>{r.data.name} • {r.data.quantity}</h3><p>{tm(r.data.cost)} • {r.data.reason}</p><small>{new Date(r.created).toLocaleString("fa-IR")}</small></article>)}</section></div>}
 {view==="next"&&<section className="panel"><h2>در برنامه ساخت</h2><p>ویرایش نسخه‌دار، ورود Excel و فاکتور، قیمت دیجی‌کالا، ماندگاری موجودی، فروش و پیک، هزینه‌های جاری، تحلیل منو، تبلیغات، دارایی و دستیار گفتگو هنوز عملیاتی نشده‌اند.</p><p>این نسخه برای حساب فعلی یک مجموعه نگه می‌دارد؛ دعوت کارکنان و پنل واقعی مدیر کل در مرحله بعد پیاده می‌شوند.</p></section>}
 </>}<footer>اطلاعات در حساب مجموعه ذخیره می‌شود؛ با بستن صفحه پاک نمی‌شود. قیمت‌ها را کاربر ثبت می‌کند و اتصال قیمت آنلاین فعال نیست.</footer></main></SidebarInset><Toaster position="top-center" dir="rtl"/></SidebarProvider>
}
