import ts from 'typescript';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync,writeFileSync,mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {pathToFileURL} from 'node:url';
import assert from 'node:assert/strict';
const dir=mkdtempSync(join(tmpdir(),'diner-expenses-'));
try{
for(const name of ['expenses','stock','cost'])writeFileSync(join(dir,name+'.mjs'),ts.transpile(readFileSync(`lib/${name}.ts`,'utf8'),{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ES2022}).replaceAll("'./cost'","'./cost.mjs'").replaceAll("'./stock'","'./stock.mjs'"));
const {period,expenseData,allocateExpense,reportPeriod,changeExpense}=await import(pathToFileURL(join(dir,'expenses.mjs')));
assert.equal(period('2024-02-01','2024-02-29').days,29);
for(const args of [['2024-02-30','2024-03-01'],['2024-03-02','2024-03-01'],['2024-01-01','2025-01-01']])assert.throws(()=>period(...args));
const e=expenseData({title:'Rent',category:'rent',total:'۱۰',from:'2024-02-01',to:'2024-02-03',source:'test'});
assert.equal(e.total,100);assert.equal(allocateExpense(e,e.from,e.to),100);
assert.equal(allocateExpense(e,e.from,e.from)+allocateExpense(e,'2024-02-02',e.to),100);
assert.equal(allocateExpense(e,'2024-03-01','2024-03-31'),0);
assert.throws(()=>expenseData({...e,total:0}));
const sql=new DatabaseSync(':memory:');
for(const file of ['0000_lyrical_speed_demon.sql','0001_white_queen_noir.sql'])sql.exec(readFileSync('drizzle/'+file,'utf8'));
for(const id of ['r','other'])sql.prepare('INSERT INTO restaurants VALUES (?,?,?,?,?)').run(id,id,id,'test','2024-01-01');
const db={prepare(query){return {bind(...args){return {sql:query,args,async first(){return sql.prepare(query).get(...args)||null},async all(){return {results:sql.prepare(query).all(...args)}},async run(){return sql.prepare(query).run(...args)}}}}},async batch(ss){sql.exec('BEGIN');try{for(const s of ss)sql.prepare(s.sql).run(...s.args);sql.exec('COMMIT')}catch(e){sql.exec('ROLLBACK');throw e}}};
const put=(id,kind,data,owner='r',created='2024-02-01T10:00:00.000Z')=>sql.prepare('INSERT INTO records VALUES (?,?,?,?,?)').run(id,owner,kind,JSON.stringify(data),created);
put('rent','expense',e);put('foreign','expense',{...e,total:100000},'other');
for(let i=0;i<1001;i++)put('sale'+i,'sale',{day:'2024-02-01',gross:200,contribution:100,count:1});
put('void-sale','sale',{day:'2024-02-01',contribution:99999,voided:true});
put('foreign-sale','sale',{day:'2024-02-01',contribution:99999},'other');
put('w1','waste',{cost:7},'r','2024-01-31T20:30:00.000Z');
put('w2','waste',{cost:500},'r','2024-01-31T20:29:59.999Z');
let report=await reportPeriod(db,'r','2024-02-01','2024-02-03');
assert.equal(report.saleEntries,1001);assert.equal(report.overhead,100);assert.equal(report.waste,7);assert.equal(report.operatingBalance,100100-100-7);assert.equal(report.paidExpenses,0);
await assert.rejects(()=>changeExpense(db,'other','bad',{kind:'pay_expense',expenseId:'rent',paidOn:'2024-02-02'}));
const broken={...db,async batch(ss){return db.batch([...ss.slice(0,1),{sql:'UPDATE missing SET x=1',args:[]},...ss.slice(1)])}};
await assert.rejects(()=>changeExpense(broken,'r','broken',{kind:'pay_expense',expenseId:'rent',paidOn:'2024-02-02'}));
assert.equal(sql.prepare("SELECT count(*) n FROM records WHERE kind='expense_payment'").get().n,0);
await changeExpense(db,'r','payment',{kind:'pay_expense',expenseId:'rent',paidOn:'2024-03-01'});
await changeExpense(db,'r','retry',{kind:'pay_expense',expenseId:'rent',paidOn:'2024-03-01'});
assert.equal(sql.prepare("SELECT count(*) n FROM records WHERE kind='expense_payment'").get().n,1);
report=await reportPeriod(db,'r','2024-02-01','2024-02-03');assert.equal(report.overhead,100);assert.equal(report.paidExpenses,0);
report=await reportPeriod(db,'r','2024-03-01','2024-03-31');assert.equal(report.overhead,0);assert.equal(report.paidExpenses,100);assert.equal(report.operatingBalance,0);
await changeExpense(db,'r','void',{kind:'void_expense',expenseId:'rent',reason:'wrong entry'});
await changeExpense(db,'r','void-retry',{kind:'void_expense',expenseId:'rent',reason:'wrong entry'});
assert.equal(sql.prepare("SELECT count(*) n FROM records WHERE kind='expense_void'").get().n,1);
assert.equal((await reportPeriod(db,'r','2024-02-01','2024-03-31')).overhead,0);
await assert.rejects(()=>changeExpense(db,'r','after-void',{kind:'pay_expense',expenseId:'rent',paidOn:'2024-03-01'}));
console.log('PASS: exact period allocation, leap dates, 1001 sales, tenant isolation, Tehran boundary, separate payment, audited retries and rollback');
}finally{rmSync(dir,{recursive:true,force:true})}
